### PR TITLE
Adding ward management component

### PR DESCRIPTION
**Pull request by praveenshashee**
added pages related to ward & patient assignment
added models/routes files
edited app.js and server.js files

### CODE REVIEW

**Review by Ravindu-Ishan — CHANGES_REQUESTED** [review]
Screenshot 2024-04-24 170534


Please do the above additions to your front end pages  to make sure they are displayed properly in the given space.

Navigation missing ?

**Comment by Ravindu-Ishan** [comment]
Which page needs to be connected to dashboard Manage wards link ?

image

**Comment by praveenshashee** [comment]
I need my Ward_home page in Ward_components to be connected to the dashboard Manage wards link.

**Review by Ravindu-Ishan — APPROVED** [review]

**Review by Ravindu-Ishan — APPROVED** [review]
Approving, additions to pages still required, content will not be displayed properly.

**Pull request merged**
